# Generated by Django 3.0.6 on 2020-09-29 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_accounts', '0002_auto_20200929_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='send_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
