# Generated by Django 3.0.6 on 2020-10-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_accounts', '0003_auto_20200929_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ban_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_baned',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(choices=[('Academy Student', 'academy'), ('Genin', 'genin'), ('Chuunin', 'chuunin'), ('Jounin', 'jounin'), ('ANBU', 'anbu'), ('Sannin', 'sannin'), ('Kage', 'kage')], default='Academy Student', max_length=40),
        ),
    ]
