# Generated by Django 3.0.6 on 2020-10-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_accounts', '0005_auto_20201007_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_baned',
            field=models.BooleanField(default=False),
        ),
    ]
