# Generated by Django 3.0.6 on 2020-10-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_accounts', '0007_auto_20201007_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ban_time',
        ),
    ]

    
    
    
    
    
    
    
    
    
    
    
    
    
    
