# Generated by Django 3.0.6 on 2020-09-29 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='question', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(default='quiz', max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='quiz_img')),
                ('preview_field', models.TextField(blank=True)),
                ('timer', models.PositiveSmallIntegerField(null=True)),
                ('attempt_time', models.PositiveSmallIntegerField(null=True)),
                ('questions_count', models.PositiveSmallIntegerField(null=True)),
                ('publucation_time', models.DateTimeField(blank=True, null=True)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizzResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.PositiveSmallIntegerField()),
                ('scores', models.PositiveSmallIntegerField(null=True)),
                ('duration', models.CharField(max_length=15, null=True)),
                ('result_link', models.SlugField(null=True)),
                ('result_time', models.DateTimeField(null=True)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quizzes')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(null=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Questions')),
                ('quiz_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizzResult')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quizzes',
            name='people_passed',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.QuizzResult'),
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quizzes'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='comment', max_length=300)),
                ('publicationDate', models.DateTimeField()),
                ('user_img', models.CharField(blank=True, max_length=80)),
                ('is_edited', models.BooleanField(default=False)),
                ('quizComment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quizzes')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='quiz.Comments')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publicationDate',),
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='answer', max_length=100)),
                ('complete', models.BooleanField(verbose_name='Correct')),
                ('question_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Questions')),
            ],
        ),
    ]
