# Generated by Django 3.0.6 on 2020-09-29 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200929_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='publucation_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='quizzresult',
            name='result_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
