# Generated by Django 3.0.6 on 2020-09-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200929_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_multiple_answers',
            field=models.BooleanField(null=True),
        ),
    ]
