# Generated by Django 3.0.6 on 2020-09-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_questions_is_multiple_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='is_multiple_answers',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
