# Generated by Django 3.0.6 on 2020-09-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200929_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='is_multiple_answers',
            field=models.BooleanField(blank=True),
        ),
    ]
