# Generated by Django 3.0.6 on 2020-10-11 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0009_questions_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='quiz',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='timer',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
