# Generated by Django 3.0.6 on 2020-10-17 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20201011_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='questions_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='quiz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='quiz_img/questions')),
                ('is_multiple_answers', models.BooleanField(blank=True)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quizzes')),
            ],
        ),
    ]
