# Generated by Django 3.0.6 on 2020-10-17 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20201017_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, null=True)),
                ('complete', models.BooleanField(verbose_name='Correct')),
                ('question_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Questions')),
            ],
        ),
    ]
