# Generated by Django 3.0.6 on 2020-10-18 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_gameanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamequestion',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='GameAnswer',
        ),
        migrations.DeleteModel(
            name='GameQuestion',
        ),
    ]
