# Generated by Django 3.0.6 on 2020-10-19 17:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20201018_0134'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='questions',
            managers=[
                ('randoms', django.db.models.manager.Manager()),
            ],
        ),
    ]
