# Generated by Django 3.0.6 on 2020-10-20 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20201019_1726'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='questions',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='GameQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='question', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='quiz_img/questions')),
                ('is_multiple_answers', models.BooleanField(blank=True)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quizzes')),
            ],
        ),
    ]
