# Generated by Django 3.0.6 on 2020-10-20 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20201020_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.GameQuestions'),
        ),
    ]
