# Generated by Django 3.0.6 on 2020-10-20 23:48

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20201020_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestions',
            name='image',
            field=models.ImageField(blank=True, upload_to=quiz.models.avatar_upload_to),
        ),
    ]
