# Generated by Django 3.0.6 on 2020-10-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20201020_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestions',
            name='image',
            field=models.ImageField(blank=True, upload_to='quiz_img/game_questions'),
        ),
    ]
