# Generated by Django 3.0.6 on 2020-10-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_auto_20201022_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestions',
            name='image',
            field=models.CharField(max_length=150),
        ),
    ]
