# Generated by Django 3.0.6 on 2020-10-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20201023_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestions',
            name='image',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
