# Generated by Django 3.0.6 on 2020-10-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_gameanswers_quiz_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedAnswer',
        ),
    ]
