# Generated by Django 3.0.6 on 2020-11-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_delete_selectedanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzresult',
            name='is_successfully_passed',
            field=models.BooleanField(null=True),
        ),
    ]
