# Generated by Django 3.0.6 on 2020-11-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_quizzresult_is_successfully_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzresult',
            name='is_successfully_passed',
            field=models.BooleanField(),
        ),
    ]
