# Generated by Django 3.0.6 on 2020-11-07 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_auto_20201104_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameanswers',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quizzes'),
        ),
    ]
