# Generated by Django 3.0.6 on 2020-11-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_gameanswers_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_img',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='gamequestions',
            name='image',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='people_passed',
            field=models.ManyToManyField(blank=True, to='quiz.QuizzResult'),
        ),
    ]
